package demo.dao;

import demo.model.SysRelation;
import demo.model.SysRelationExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SysRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbg.generated
     */
    long countByExample(SysRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbg.generated
     */
    int deleteByExample(SysRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbg.generated
     */
    int insert(SysRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbg.generated
     */
    int insertSelective(SysRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbg.generated
     */
    List<SysRelation> selectByExample(SysRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbg.generated
     */
    SysRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysRelation record, @Param("example") SysRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysRelation record, @Param("example") SysRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysRelation record);
}